#!/bin/zsh

BASE=$(dirname $0)
BU_DIR=$BASE/backup

PREFIX=$(date "+%Y%m%d%H%M%S")

code --list-extensions > ${BU_DIR}/${PREFIX}_code.extensions.txt
ls /Applications/      > ${BU_DIR}/${PREFIX}_applications.txt
