brew 'git'
brew 'tmux'
brew 'tmux-xpanes'
brew 'jq'        # JSON
brew 'python-yq' # Yaml
brew 'fzf'
brew 'ghq'

# Development tools
brew 'xz'
brew 'nkf'
brew 'openssl'
brew 'autoconf'
brew 'automake'
brew 'coreutils'

brew 'graphviz'  # Graph Visualization
brew 'watchman'  # watching changes in the filesystem

# brew 'redis'
# brew 'pkgdiff'
# brew 'rsync'
brew 'fn'

# Lang
## Go
# brew 'go@1.11'
# brew 'dep'

## Node
# brew 'node@10'
brew 'yarn', args: [ 'ignore-dependencies' ]

brew 'qemu'
brew 'iperf'

# dev nes
# brew 'portaudio'

# Cloud management tools
## AWS
brew 'awscli'
## GCP
# brew 'firebase-cli'

# Provisioning
brew 'terraform'
brew 'packer'
brew 'ansible'
  
# Cask
cask 'qlmarkdown'
cask 'ngrok'

