brew 'zsh'
brew 'git'
brew 'git-lfs'
brew 'tmux'
brew 'tmux-xpanes'
brew 'jq'        # JSON
brew 'python-yq' # Yaml
brew 'fzf'       # command-line fuzzy finder
brew 'ghq'
brew 'xz'        # Compress or decompress
brew 'nkf'       # Network Kanji Filter
# brew 'graphviz'  # Graph Visualization
# brew 'watchman'  # Watching changes in the filesystem

brew 'openssl'
brew 'autoconf'
brew 'automake'
brew 'coreutils'

brew 'qemu'
# brew 'iperf'
# brew 'iperf3'
brew 'htop'

# Cloud management tools
brew 'awscli'

# React Native
tap 'facebook/fb'
brew 'idb-companion'

# Multimedia
brew 'youtube-dl'
brew 'ffmpeg'
# brew 'flac'
# brew 'lame'
# brew 'shntool'
# brew 'cuetools'
# cask 'calibre'
# cask 'yacreader'

# Cask
cask 'osxfuse'
cask 'xquartz'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'google-drive-file-stream'
cask 'iterm2'
cask 'alfred'
cask 'ngrok'
cask 'paw'
cask 'fork'
cask 'slack'
cask 'jetbrains-toolbox'
cask 'homebrew/cask-versions/visual-studio-code-insiders'
cask 'docker-edge'
cask 'sequel-pro-nightly'
cask 'veracrypt'
cask 'firefox'
cask 'notion'
cask 'vlc'

# App Store
brew 'mas'
mas 'Xcode', id: 497799835
mas 'Magnet', id: 441258766
mas 'TweetDeck', id: 485812721
mas 'The Unarchiver', id: 425424353
mas 'LINE', id: 539883307
mas 'ZIPANG', id: 882655968
