#!/bin/zsh

args=${@:-HEAD}
([ \"$args\" = \"HEAD\" ] && git status --short || git diff --name-status $args | sed 's/\t/  /') | \
    fzf --preview 'echo {} | cut -c 4- | xargs git diff --color=always $args --' --multi | \
    cut -c 4-
